### ISSUE TITLE
Refactor suggestion fo API calls!

### ISSUE THREAD

**Issue by noyamirai** [RainbowJM/web-app-from-scratch-2223#2]
Hi! I've been looking at your code for the code reviews and wanted to share a few suggestions with you regarding your javascript script! 😄 

https://github.com/RainbowJM/web-app-from-scratch-2223/blob/f625004184dd774367017962f9972d2c731fe868/spa/index.js#L10-L48

You're fetching and displaying your data, which is cool!! I did however notice it kinda breaks when you're trying to reset the 'counter' or index of your data array. Not to sound like a huge nerd, but I dove into your code because I was interested in why it broke hehe 🤓 

The reason why it kind of breaks is because you're checking the following statement `counter == info.length`, which won't work the way you expect it to! Since arrays start counting at zero, it was trying to access an item by array key that does not exist. I also have another suggestion regarding the way you handle your api calls! Please note that the way you fetch your data is fine, I just wanted to share another way of handing it 😄 See code below!

```javascript
let dataFromApi;
let index = 0;

// no async needed on load
window.onload = () => {
    displayData();
};

async function displayData() {

    try {
        const data = await promiseOfSomeData();

        dataFromApi = data;

        title.innerHTML = data[index].author;
        bio.innerHTML = data[index].bio;
        quote.innerHTML = data[index].quote;
        
    // Handle your errors!
    } catch (error) {
        console.log(error);
    }
}

async function promiseOfSomeData() {

    try {

        const response = await fetch(url);

        if (response.status >= 200 && response.status <= 299){
            const result = await response.json();
            return result;

        // Status error
        }else {
            throw Error(r.statusText);
        }
        
    // Fetch error
    } catch (error) {
        throw new Error(error);
    }
}

button.addEventListener("click", () => {

    // Length of array is not same as 'index length' (starts at 0) 
    if (index == (dataFromApi.length - 1)) {
        index = 0;   
    } else {
        index++;
    }

    // Always set content! The only thing that changes is your array index
    title.innerHTML = dataFromApi[index].author;
    bio.innerHTML = dataFromApi[index].bio;
    quote.innerHTML = dataFromApi[index].quote;

});

```

Hope this helps or provides new insights! If you ever need help or have questions let me know!

**Comment by RainbowJM** [comment]
Thanks for debugging the code and the suggestions
