### ISSUE TITLE
Review HTML structure

### ISSUE THREAD

**Issue by noyamirai** [RainbowJM/web-app-from-scratch-2223#3]
Hi, me again!

I have some other feedback, this time related to your HTML! I think you could maybe approach your structure differently. Right now, it seems as though you are using a lot of wrappers/containers, when you would do fine without the div for example! Inside your `<div class="blog">` you're using another `div` for the title, but if you were to remove the `div` parent you could have the section as it's wrapper and instead of using a `div` for the title wrapper, you could use `header` !

Hope this helps !

https://github.com/RainbowJM/web-app-from-scratch-2223/blob/f625004184dd774367017962f9972d2c731fe868/spa/index.html#L21-L43

**Comment by RainbowJM** [comment]
Thanks for debugging the code and the suggestions
