### ISSUE TITLE
Laiba Feedback

### ISSUE THREAD

**Issue by laibaaac** [RainbowJM/web-app-from-scratch-2223#5]
Tips:
- de vscode live server file zou ik even weghalen, is niet relevant
- Ik zou even de repo opschonen, de files van de geforkte repo moet namelijk weg 
- ik zou in de about meer over je website zetten, een korte beschrijving 
- ik zou de readme aanpassen en een korte beschrijving van je opdracht, user story, api en schetsen / design geven. 
- Ik zou ook de code van visitekaartje weghalen, zet alleen je eindopdracht erin 
- in de code kan je wat comments achterlaten om je code leesbaar te maken 
- ik zie in je html bij de main je div die je hebt genest, maar is dat echt nodig? (probeer divs in divs in divs te vermijden, het gaat snel slordig worden, bij cttr begrijp ik het wel)
- Om een section semantisch correct te hebben, moet je altijd een h1 of h2, h3 ofzo erin zetten (die kan je dan evt in css verstoppen

Tops:
- een hele mooie structuur gehouden
- nog wel te volgen code
- relevante benoemingen van code 
- best heel ver! echt nice gedaan!!!!

**Comment by RainbowJM** [comment]
Thanks for your feedback
